### ISSUE TITLE
gtun2.0.5客户端无法连接服务端，也没有生成日志，请帮忙排查。

### ISSUE THREAD

**Issue by Sirius2016** [ICKelin/gtun#10]
服务端操作系统：CentOS Stream release 8
gtund版本：2.0.5
服务端监听正常，3002和3003，6060是什么端口
![image](https://github.com/ICKelin/gtun/assets/23203953/8e73b341-59dd-4130-ab8c-19de3d45f1f6)

服务端配置：
```yml
trace: ":3003"
server:
  - listen: ":3002"
    authKey: "20232024"
    scheme: "kcp"

log:
  days: 5
  level: "debug"
  path: "gtund.log"
```

客户端：centos7
gtun版本：2.0.5
客户端只监控了：6060端口
![image](https://github.com/ICKelin/gtun/assets/23203953/c1f43af8-fc76-4ef6-9dbb-219025f33071)

客户端配置：

```yml
settings:
  CN:
    # 代理ip文件，可以是本地文件，也可以是网络文件，一行是一个IP或者cidr
    proxy_file: "https://www.ipdeny.com/ipblocks/data/countries/us.zone"
    route:
      # 拨测地址，需要修改CN_SERVER_IP和CN_SERVER_TRACE_PORT，对应gtund的公网IP和端口
      - trace_addr: 137.175.63.1:3003
        scheme: "kcp"
        # 服务端地址，修改为对应gtund的IP和端口
        addr: 137.175.63.1:3002
        auth_key: "20232024"
    proxy:
      # 代理插件配置
      "tproxy_tcp": |
        {
          "read_timeout": 30,
          "write_timeout": 30,
          "listen_addr": ":8524",
          "rate_limit": 50,
          "region": "CN"
        }
      "tproxy_udp": |
        {
          "read_timeout": 30,
          "write_timeout": 30,
          "session_timeout": 30,
          "listen_addr": ":8524",
          "rate_limit": 50,
          "region": "CN"
        }
log:
  days: 5
  level: Debug
  path: gtun.log

http_server:
  listen_addr: ":9001"
```
